blogger_api/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


BASE_URL = "api"
VERSION_1_BASE_URL = "v1"


urlpatterns = [
    # INTERNATIONALIZATION
    path("i18n/", include("django.conf.urls.i18n")),
    
    # 3rd party apps URLs
    path("summernote/", include("django_summernote.urls")),
    path("rest/framework/", include("rest_framework.urls")),
    
    # Locale API apps URLs
    path(f"{BASE_URL}/{VERSION_1_BASE_URL}/", include("blogger_api.v1_urls", namespace="api-v1")), # v1 base URLs entry point
]

# Translated URLs
urlpatterns += i18n_patterns(
    # Django admin
    path(f"{settings.DJANGO_ADMIN_PAGE_URL}/admindocs/", include("django.contrib.admindocs.urls")), # Must appear before admin.site.urls
    path(f"{settings.DJANGO_ADMIN_PAGE_URL}/", admin.site.urls),
    
    # Locale templates apps URLs
    path("", include("core.urls", namespace="templates-core")),
    
    prefix_default_language=True
)


# API UI Docs URLs
urlpatterns += [
    path(f"{BASE_URL}/docs/", include("docs.urls", namespace="docs")),
]


# Django Browser Reload
urlpatterns += [
    path("__reload__/", include("django_browser_reload.urls")),
]


# Serving static and media files
urlpatterns += static(settings.STATIC_URL, serve, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, serve, document_root=settings.MEDIA_ROOT)

core/urls.py
from core import views
from django.urls import path

app_name = "templates-core"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

urlpatterns += [
    path("set-language/<str:lang_code>/", views.set_language_view, name="set-language"),
]

docs/urls.py
from docs import views
from django.urls import re_path, path

app_name = "docs"

urlpatterns = [
   path("", views.api_documentation.with_ui("redoc", cache_timeout=0), name="api-schema-redoc"),
   path("ui/", views.api_documentation.with_ui("swagger", cache_timeout=0), name="api-schema-swagger-ui"),
   re_path(r"^swagger(?P<format>\.json|\.yaml)$", views.api_documentation.without_ui(cache_timeout=0), name="api-schema-json"),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from accounts.models import User
from django.utils.translation import gettext_lazy as _


class LoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control form-control-sm",
                "placeholder": "john@doe.org",
                "autocomplete": "email"
            }
        )
    )
    
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-sm",
            }
        )
    )



class CreateUserForm(forms.ModelForm):
    username = forms.CharField(
        required=True, 
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-sm",
                # "pattern": "^[a-zA-Z0-9]{4,}$",
            }
        )
    )
    
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(
            attrs={ 
                "class": "form-control form-control-sm",
            }
        )
    )
    
    password = forms.CharField(
        required=True, 
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-sm",
                # "pattern": "^(?=.*[a-z])(?=.*[A-Z]).{8,}$",
            }
        )
    )
    
    password2 = forms.CharField(
        required=True, 
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-sm",
                # "pattern": "^(?=.*[a-z])(?=.*[A-Z]).{8,}$",
            }
        )
    )
    
    
    class Meta:
        model = User
        fields = ["username", "email", "password"]

    def clean(self):
        cleaned_data = super(CreateUserForm, self).clean()
        if cleaned_data["password"] != cleaned_data["password2"]:
            raise forms.ValidationError(_("Les deux mots de passe ne concordent pas!"))
    
    def save(self, *args, **kwargs) -> User:
        cleaned_data = super(CreateUserForm, self).clean()
        user = User.objects.create_superuser(
            email=cleaned_data["email"],
            username=cleaned_data["username"],
            password=cleaned_data["password"]
        )
        return user

core/views.py
from django.conf import settings
from django.contrib import messages
from django.urls import translate_url
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.utils.translation import check_for_language
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest

from accounts.models import User
from core.forms import LoginForm, CreateUserForm
from core.decorators import unauthenticated_user


@login_required(login_url="templates-core:login")
def home_view(request):
    context = {}
    template_name = "home.html"
    return render(request, template_name, context)


def set_language_view(request: HttpRequest, lang_code: str):
    """Custom language setting view. Django default accepts only POST request. I don't want that.
        (It's not safe. Use at your own risks)

    Args:
        request (HttpRequest): Django HttpRequest
        lang_code (str): Code of the language to set (choices are in {settings.LANGUAGES})

    Returns:
        HttpResponse | HttpResponseRedirect: Return response or redirect to the previous page
    """
    try:
        next_url = request.META.get("HTTP_REFERER")
    except:
        next_url = "/"
    response = HttpResponseRedirect(next_url) if next_url else HttpResponse(status=204)
    if lang_code and check_for_language(lang_code):
        if next_url:
            next_trans = translate_url(next_url, lang_code)
            if next_trans != next_url:
                response = HttpResponseRedirect(next_trans)
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME,
            lang_code,
            max_age=settings.LANGUAGE_COOKIE_AGE,
            path=settings.LANGUAGE_COOKIE_PATH,
            domain=settings.LANGUAGE_COOKIE_DOMAIN,
            secure=settings.LANGUAGE_COOKIE_SECURE,
            httponly=settings.LANGUAGE_COOKIE_HTTPONLY,
            samesite=settings.LANGUAGE_COOKIE_SAMESITE,
        )
    return response




@unauthenticated_user
def login_view(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST) or None
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            
            user = authenticate(request, email=email, password=password)
            if user is not None and user.is_active:
                login(request, user)
                messages.success(request, _("Bon retour à vous!"))
                
                # You may send login alert (using celery for example)

                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                try:
                    return redirect(user.dashboard_url())
                except:
                    return redirect("/")
            else: # user is None or inactive
                messages.warning(request, _("Mot de passe ou email incorrect!"))
        
        else:  # if not form.is_valid()
            errors = form.errors.as_data()
            for error in errors:
                msg = "".join(errors[error][0])
                messages.error(request, _(f"{error.capitalize()}: {msg}"))
            return redirect(".")
    
    context = {
        "form": form,
    }
    template_name = "login.html"
    return render(request, template_name, context)




@login_required(login_url="templates-core:login")
def logout_view(request):
    logout(request)
    messages.success(request, _("Vous vous êtes déconnecté(e) avec succès. À bientôt !"))
    try:
        return redirect(request.META.get("HTTP_REFERER"))
    except:
        return redirect("/")





@unauthenticated_user
def register_view(request):
    """ Register new users (all users created using this view are superuser by default) """
    form = CreateUserForm
    if request.method == "POST":
        form = CreateUserForm(request.POST) or None
        if form.is_valid():
            cleaned_data = form.cleaned_data
            created_user: User = form.save() # Create user object
            
            # Send welcome email to user (with confirmation link)
            
            
            # Sign in the current user
            user = authenticate(request, email=cleaned_data["email"], password=cleaned_data["password"])
            if user is not None and user.is_active:
                login(request, user)
                messages.success(request, _(f"Compte admin créé avec succès!"))
                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                return redirect("/")
            else:
                messages.info(request, _("Veuillez vous connecter pour accéder à votre tableau de bord !"))
                return redirect("templates-core:login")
        
        else:  # if not form.is_valid()
            errors = form.errors.as_data()
            for error in errors:
                msg = "".join(errors[error][0])
                messages.error(request, _(f"{error.capitalize()}: {msg}"))
            return redirect(".")
            
    else: # request.method != "POST"
        form = CreateUserForm()
    
    context = {
        "form": form,
    }
    template_name = "register.html"
    return render(request, template_name, context)

core/templates/home.html
{% extends "public/base.html" %}

{% load i18n %}

{% block title %}
    {% trans "Accueil" %} :: {{ site_name }}
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-md-12 col-12 col-lg-12 py-5 text-center">
                <div class="alert alert-info p-3">
                    {% trans "API minimaliste d'un exemple de blog personnel. Seules quelques fonctionnalités basiques ont été prises en compte." %} <br>
                    {% trans "Il y a entre autres :" %}
                    <ul class="list-unstyled mt-2 fw-bold">
                        <li>{% trans "Le système d'authentification (par email)." %}</li>
                        <li>{% trans "Une lucarne pour recevoir des messages (contacts)" %}</li>
                        <li>{% trans "Une lucarne pour pour la newsletter (souscriptions en l'occurence; pas tout)" %}</li>
                        <li>…</li>
                    </ul>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-4 col-6 col-lg-3 my-2">
                <div class="card rounded-2 p-3 text-center">
                    <p class="mb-3">
                        {% trans "Documentation interactive de l'API avec un visuel dynamique. Possible de tester les endpoints." %}
                    </p>
                    <a href="{% url 'docs:api-schema-swagger-ui' %}" target="_blank" class="btn btn-primary btn-sm">
                        {% trans "API UI Docs" %}
                    </a>
                </div>
            </div>

            <div class="col-md-4 col-6 col-lg-3 my-2">
                <div class="card rounded-2 p-3 text-center">
                    <p class="mb-3">
                        {% trans "Documentation régulière avec les types de réponses de l'API avec un visuel dynamique." %}
                    </p>
                    <a href="{% url 'docs:api-schema-redoc' %}" target="_blank" class="btn btn-info btn-sm">
                        {% trans "API Regular Docs" %}
                    </a>
                </div>
            </div>

            <div class="col-md-4 col-6 col-lg-3 my-2">
                <div class="card rounded-2 p-3 text-center">
                    <p class="mb-3">
                        {% trans "Documentation des modèles gabarits, balises, filtres, liens, vues et signets" %}
                    </p>
                    <a href="{% url 'django-admindocs-docroot' %}" target="_blank" class="btn btn-success btn-sm">
                        {% trans "Consulter" %}
                    </a>
                </div>
            </div>

            <div class="col-md-4 col-6 col-lg-3 my-2">
                <div class="card rounded-2 p-3 text-center">
                    <p class="mb-3">
                        {% trans "Administration Django" %}
                    </p>
                    <a href="{% url 'admin:index' %}" target="_blank" class="btn btn-outline-danger btn-sm">
                        {% trans "Admin" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/login.html
{% extends "public/base.html" %}

{% load i18n cache %}

{% block title %}
    {% trans "Connexion" %} :: {{ site_name }}
{% endblock title %}


{% block extra_head %}
    <style>
        label {
            font-weight: normal !important;
            font-size: small !important;
            text-transform: uppercase !important;
        }
    </style>
{% endblock extra_head %}


{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-md-12 col-12 col-lg-12 py-5">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-2"></div>

                        <div class="col-12 col-sm-12 col-md-8">

                            <div class="card rouded-3 p-4">
                                <h1 class="h4 my-2 text-center">{% trans "Connectez-vous" %}</h1>
                                <div class="card-body">
                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.email.auto_id }}" class="float-end">
                                                {% trans "Adresse électronique" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.email }}
                                        </div>
                                    </div>

                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.password.auto_id }}" class="float-end">
                                                {% trans "Mot de passe" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.password }}
                                        </div>
                                    </div>


                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4"></div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            <input id="togglePasswordId" type="checkbox" class="form-check-input me-2" onclick="togglePassword()">
                                            <label for="togglePasswordId">
                                                {% trans "Afficher le mot de passe" %}
                                            </label>
                                        </div>
                                    </div>

                                    {% if request.GET.next %}
                                        <input type="hidden" name="next" value="{{ request.GET.next }}" />
                                    {% endif %}

                                    <div class="row my-4">
                                        <div class="col-3 col-sm-4 col-md-4"></div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            <div class="row gap-1 d-grid">
                                                <button class="btn btn-success btn-sm">
                                                    {% trans "Connexion" %}
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <p>
                                    <span class="float-start">
                                        {% trans "Créez" %}
                                        <a href="{% url 'templates-core:register' %}" class="text-decoration-none">
                                            {% trans "un compte admin" %}
                                        </a>
                                    </span>
                                </p>
                            </div>
                        
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}


{% block extra_scripts %}
    <script>
        // Toggle password
        var password = document.getElementById("{{ form.password.auto_id }}");
        function togglePassword() {
            if (password.type === "password") {
                password.type = "text";
            } else {
                password.type = "password";
            }
        }
    </script>
{% endblock extra_scripts %}

core/templates/register.html
{% extends "public/base.html" %}

{% load i18n cache %}

{% block title %}
    {% trans "Inscription" %} :: {{ site_name }}
{% endblock title %}



{% block extra_head %}
    <style>
        label {
            font-weight: normal !important;
            font-size: small !important;
            text-transform: uppercase !important;
        }
    </style>
{% endblock extra_head %}


{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-md-12 col-12 col-lg-12 py-5">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-2"></div>

                        <div class="col-12 col-sm-12 col-md-8">

                            <div class="card rouded-3 p-4">
                                <h1 class="h5 my-2 text-center">{% trans "Créez votre compte admin" %}</h1>
                                <div class="card-body">
                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.email.auto_id }}" class="float-end">
                                                {% trans "Adresse électronique" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.email }}
                                        </div>
                                    </div>

                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.username.auto_id }}" class="float-end">
                                                {% trans "Nom d'utilisateur" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.username }}
                                        </div>
                                    </div>

                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.password.auto_id }}" class="float-end">
                                                {% trans "Mot de passe" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.password }}
                                        </div>
                                    </div>

                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4">
                                            <label for="{{ form.password2.auto_id }}" class="float-end">
                                                {% trans "Confirmer" %}
                                                <sup class="text-danger">*</sup>
                                            </label>
                                        </div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            {{ form.password2 }}
                                        </div>
                                    </div>


                                    <div class="row my-3">
                                        <div class="col-3 col-sm-4 col-md-4"></div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            <input id="togglePasswordId" type="checkbox" class="form-check-input me-2" onclick="togglePassword()">
                                            <label for="togglePasswordId">
                                                {% trans "Afficher le mot de passe" %}
                                            </label>
                                        </div>
                                    </div>

                                    {% if "next" in request.META.HTTP_REFERER %}
                                        <input type="hidden" name="next" id="next_url_id" value="{{ request.GET.next }}" />
                                    {% endif %}

                                    <div class="row my-4">
                                        <div class="col-3 col-sm-4 col-md-4"></div>
                                        <div class="col-9 col-sm-8 col-md-8">
                                            <div class="row gap-1 d-grid">
                                                <button class="btn btn-primary btn-sm">
                                                    {% trans "Inscription" %}
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                    <p>
                                        <span class="float-start">
                                            {% trans "Vous avez déjà un compte ?" %}
                                            <a href="{% url 'templates-core:login' %}" class="text-decoration-none">
                                                {% trans "Connectez-vous" %}
                                            </a>
                                        </span>
                                    </p>
                                </div>
                            </div>
                        
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}


{% block extra_scripts %}
    <script>
        var password = document.getElementById("{{ form.password.auto_id }}");
        var password2 = document.getElementById("{{ form.password2.auto_id }}");
        function togglePassword() {
            if (password.type === "password") {
                password.type = "text";
                password2.type = "text";
            } else {
                password.type = "password";
                password2.type = "password";
            }
        }
    </script>

    {% if "next" in request.META.HTTP_REFERER %}
        <script>
            // if "next" in previous, then run this script.
            // check if value of input (named "next") is empty. If not, don't do anything else set its value to request.META.HTTP_REFERER

            // console.log("'next' in previous URL!")
            next_url_input = document.getElementById("next_url_id");
            if (next_url_input.value == "") {
                next_url_input.value = "{{ request.META.HTTP_REFERER }}";
                // console.log(next_url_input.value)
            }
        </script>
    {% endif %}
{% endblock extra_scripts %}